title: Your awesome title
author: GitHub User
email: your-email@domain.com
theme: minima
description: > this is my new description
  I've already edited it!
  And it works really cool! I like it!

# social links
twitter_username: alekssamos # DO NOT include the @ character, or else the build will fail!
github_username:  alekssamos # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
